### ISSUE TITLE
Training: ModuleNotFoundError

### ISSUE THREAD

**Issue by Phhofm** [kynthesis/StarSRGAN#4]
Thanks for your interesting work :)

I just had a quick question, when I tried out training a starsrgan light model, with your training command, I somehow got a ModuleNotFoundError:

PS D:\StarSRGAN> python .\starsrgan\train.py -opt .\options\2xNomosUniStarsrgan_light.yml
Traceback (most recent call last):
  File "D:\StarSRGAN\starsrgan\train.py", line 3, in <module>
    from starsrgan.utils.train import train_pipeline
ModuleNotFoundError: No module named 'starsrgan'

I am not sure why this is or what the correct solution were. It worked after I copied train.py and __init__.py from the starsrgan folder into the main folder aswell and just ran python train.py -opt *optionsfile* but not sure if that is a correct solution. Also trained a testmodel for around 19k iter but if I use it with inference_starsrgan.py it produces a black output image, probably because I broke something with copying the two files into their parent folder. (also id rather like to give a path to a specific .pth file as input argument rather than some model name where it searches for a hardcoded net_g_latest.pth file from experiments folder, also it forces a naming convention for the model names, model name needs to start with 'lite' for it to use the correct network/arch this way)

(PS in the Readme the finetune command needs to be adapted since its starsrgan/train.py not realesrgan/train.py, probably from copying)

Yea I simply wanted to try out StarSRGAN, looking forward for your pretrains to try out :)

**Comment by kynthesis** [comment]
On Linux, you can try to execute this command at the root directory: `export PYTHONPATH="$PWD"`

**Comment by Phhofm** [comment]
Thank you for your fast reply :) I am on a windows system currently but yea I will definetly try training on an ubuntu system when im back home (in around two weeks). Thanks :)

**Comment by Phhofm** [comment]
Ah nice just as a quick update, (on my windows system) I was able to run inference with the 19k iter starsrgan lite model I trained (with copying the train.py and __init__.py files into base folder), and it actually gave a 4x output, so it worked :)

Something is the problem on my current system with fp16, because that one gave a black output image

PS D:\StarSRGAN> python inference_starsrgan.py -i .\dearalice.png -n lite_test2 -o .
Testing 0 dearalice
2.88 FPS

But when changing to fp32 it worked and gave a correct output 

PS D:\StarSRGAN> python inference_starsrgan.py -i .\dearalice.png -n lite_test2 -o . --fp32
Testing 0 dearalice
8.44 FPS

Needed to adapt this line in the inference_starsrgan.py file (from torch.float16 to torch.float32, because otherwise the --fp32 flag as input wont work and will understandably throw an error because of missmatch (RuntimeError: Input type (struct c10::Half) and bias type (float) should be the same)
dummy_input = torch.randn(1, 3, 64, 64, dtype=torch.float32).to(device)

Nice :)

**Comment by kynthesis** [comment]
In order to save GPU memory consumption and speed up inference, StarSRGAN uses half precision (fp16) during inference by default. However, some operators for half inference are not implemented in CPU mode. You need to add **`--fp32` option** for the commands. For example, `python inference_starsrgan.py -n StarSRGANv5.pth -i inputs --fp32`.
