### ISSUE TITLE
Google Colab no module named starsrgan

### ISSUE THREAD

**Issue by ajeema** [kynthesis/StarSRGAN#6]
I'm trying to leverage google colab and locally export PYTHONPATH="$PWD" works but I cannot seem to get it to work in Google Colab. Any suggestions would be fantastic! Cheers

**Comment by ajeema** [comment]
I fixed the above by change the imports. It now tries to start the training but failed with "

`KeyError: "No object named 'L1Loss' found in 'loss' registry!"
`

**Comment by ajeema** [comment]
I resolved the above error but changing line 52 in losses/basicLoss.py from 
`return self.loss_weight * l1_loss(pred, target, weight, reduction=self.reduction)`

To 

`return self.loss_weight * F.l1_loss(pred, target, weight, reduction=self.reduction)`

**Comment by cbroker1** [comment]
hey @ajeema I'm here from the Real-ESRGAN github (link below)

https://github.com/xinntao/Real-ESRGAN

Are there tutorials out there to implement this repo?

**Comment by ajeema** [comment]
Hello @cbroker1 , Are you asking for tutorials to implement starsrgan or real-esrgan? There are none for starsrgan but I was able to get it working. For real-esrgan there are a few.

**Comment by cbroker1** [comment]
Hey @ajeema thanks for the response - starsrgan. Care to share the collab you used? :)

**Comment by ajeema** [comment]
Sure I can later when I’m by my co outer. Essentially you need to change the import paths relativity. And the other things I commented above that I fixed. Although the training consumes a lot of GPU on colab so I would recommend hosting the codes and everything on drive.

**Comment by cbroker1** [comment]
Well this made my week, thank you!

**Comment by ajeema** [comment]
So to follow up @cbroker1 :
1. Place training data and repo code in Google Drive and Connect
2. Update repo code to remove the first part of the path in all files to remove the starsrgan (for example change 
`starsrgan.utils.registry import MODEL_REGISTRY `
to 
`utils.registry import MODEL_REGISTRY`

3.change line 52 in losses/basicLoss.py from
`return self.loss_weight * l1_loss(pred, target, weight, reduction=self.reduction)
`
To

`return self.loss_weight * F.l1_loss(pred, target, weight, reduction=self.reduction)`

If you need any other help feel free to reach out

**Comment by ajeema** [comment]
@cbroker1 I actually found an easier way than removing the prefix of the imports. Move the train.py to the root folder. That will be a better option than changing all the imports as you will need to add them back for inference.

**Comment by ajeema** [comment]
I can only train the Lite model on Colab, the Full model requires too much Memory and exhausts Colab even with a + subscription. I'm running the training now and so far so good. I will test once down and Train the full model in SageMaker

**Comment by cbroker1** [comment]
I have a 4090, will I be able to run the full size model?! 24gb ram 

I have yet to crack open the repo. Looking forward to doing so this evening and on Sunday! 

Did you post the colab link somewhere?!


edit: my "plan" if you will is to train the model with frames from a 4k youtube video...then take the same video (but in 480p) and try to upscale back to 4k. what cha think?!

**Comment by ajeema** [comment]
Feel free to reach out directly to my email and I can see how I can help

mraaronjorgensen@gmail.com

**Comment by ajeema** [comment]
Yes, that GPU should be fine, Training the full consumes a lot of RAM, I think the code needs to be improved to flush cache. Or you could play with adjusting batch sizes etc. Running locally may be easier and you can more closely follow the steps in the README. Another thing that I cannot seem to get working is the auto resume. It always starts back at 0 and wipes out previous states. Looking into that while poking through the code would be beneficial. 

In terms of your "plan", yes you can train it that way, You would need to split the video into images and run the multiscale etc scripts. I'm training it on the LSDIR Training set with 4000 images. Then I will fine-tune with compressed data from h264/h265 sources. Early training results with a small number of Epochs caused color shifting, so I'm training it on more Epochs now. (800). Hopefully that resolves the issue otherwise I will need to look into how the code handles arrays.

**Comment by lilianaedmonds** [comment]
@ajeema sorry to bother you- you mention you were able to get starsrgan working and wanted to ask if you had any issues with tensor sizes incompatibilities, because have not been able to fix mine. I have been trying to get the model working for some time and keep running into issues; I describe more of the context of the problem in my post under "Issues".
